### ISSUE TITLE
sleepfix does not working fine

### ISSUE THREAD

**Issue by linhere20** [ledski31/MacbookPro2015SleepFix#2]
the 63 line(launchctl unload /Library/LaunchAgents/sleepwatcher.plist) in the sleepfix file should be removed?

**Comment by Limcap** [comment]
Hey linhere20. This script is very outdated now. Yes, there is something I had to fix in it for it to work properly, a friend of mine actually fixed it back in November 2015, but never submitted the commit. However because I returned my MacBook Pro at the time, I can't test it anymore. However I did found another solution fr the problem while googling around, that involved deleting a folder or a file in the system, I don't quite remember anymore. Anyway, I more than convinced that this problem should have been fixed by apple itself by now...

**Comment by linhere20** [comment]
I forgot this problem for a long time, recently I upgraded the system to macos seirra 10.13.2. Apple added a new setting(tcpkeepalive) to solve this problem.
to fix it  `sudo pmset -b tcpkeepalive 0`, mac not to connect to the Internet when it's asleep.
